# Generated by Django 5.0.7 on 2024-08-16 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piano', '0002_preset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='createdPresets', to=settings.AUTH_USER_MODEL),
        ),
    ]
